[package]
name = "file_system_solution"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ramdisk = {git = "https://github.com/gjf2a/ramdisk"}
thiserror-no-std = "2.0.2"